openapi: 3.1.0
info:
  title: PlacetoPay Account Validator
  version: '1.0'
  description: |
    Account Validator is a project responsible for account verification through external services.
  contact:
    url: 'https://www.evertecinc.com/pasarela-de-pagos-e-commerce/'
    name: PlacetoPay by Evertec
servers:
  - description: 'Sandbox (CO)'
    url: 'https://sites-test.placetopay.com/'
paths:
  /api/create-session:
    post:
      summary: "Create Session"
      description: "This endpoint allows you to create an account verification session."
      operationId: "create-session"
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: object
              required:
                - auth
                - user
                - returnUrl
                - locale
              properties:
                auth: 
                  $ref: "../base/en.yaml#/components/schemas/Authentication"
                user:
                  type: object
                  description: |
                    User who owns the account to be validated
                  required:
                    - name
                    - email
                  properties:
                    name:
                      type: string
                      description: |
                        First name(s) of the account owner
                      maxLength: 50
                      example: John
                    surname:
                      type: string
                      description: |
                        Last name(s) of the account owner
                      maxLength: 50
                      example: Doe
                    email:
                      type: email
                      description: |
                        Email address of the account owner
                      maxLength: 80
                      example: John.doe@test.com
                returnUrl:
                  type: string
                  description: |
                    Return URL once the account validation process is completed
                  maxLength: 255
                  example: https://www.placetopay.com/return
                locale:
                  type: string
                  description: |
                    Determines the response language
                  maxLength: 5
                  example: es_CO
                isAuthenticated:
                  type: boolean
                  description: |
                    Indicates if an external authentication process has already been performed. The intention is not to validate the user's email twice. Default is false, meaning an OTP will be sent to validate the user if they have already validated accounts with micro-deposits in the system.
                    
                  example: true
                site:
                  type: string
                  description: |
                    If use api credentials, this field is required to identificate the site
                  example: aabbccdd1234567890aabbccdd123456
      responses:
        "200":
          description: "Session created successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    description: Structure containing the response to the request if the status is successful
                    properties:
                      requestId:
                        type: string
                        description: |
                          Unique identifier of the session to be queried.
                        format: regex
                        pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
                        maxLength: 36                          
                        example: 9bd89c8d-6097-4d69-8ce9-d9b5ec35d8ea
                      redirectUrl:
                        type: string <url>
                        description: |
                          Response code
                          
                        example: https://dev-account-validator.placetopay.ws/verification/redirect/9bd89c8d-6097-4d69-8ce9-d9b5ec35d8ea
                      expiresAt:
                        type: string
                        description: |
                          Session expiration date
                          
                        example: 2024-04-19 17:36:57
                  status:
                    $ref: "../base/en.yaml#/components/schemas/Status"
        "400":
          description: |
            Invalid request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: "../base/en.yaml#/components/schemas/Status"
                required:
                  - status
  /api/check-session-status:
    post:
      summary: "Check Session Status"
      description: "This endpoint allows you to check the status of a created session."
      operationId: check-session-status
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: object
              properties:
                auth: 
                  $ref: "../base/en.yaml#/components/schemas/Authentication"
                requestId:
                  type: string
                  description: |
                    Unique identifier of the session to be queried.
                  maxLength: 36
                  example: 1f630ff7-9c02-4da4-82d4-d676709acb21
                site:
                  type: string
                  description: If use api credentials, this field is required to identificate the site                    
                  example: aabbccdd1234567890aabbccdd123456
              required:
                - auth
                - requestId
      responses:
        "200":
          description: "Successful query"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: "../base/en.yaml#/components/schemas/Status"
                  data:
                    type: object
                    description: Structure containing the response to the request if the status is successful
                    properties:
                      requestId:
                        type: string
                        description: Unique identifier of the session to be queried.
                        example: 1f630ff7-9c02-4da4-82d4-d676709acb21
                      expiresAt:
                        type: string
                        description: Session expiration date                          
                        example: 2022-08-30 15:19:33
                      account:
                        type: object
                        description: Information about the verified account (this field is available only if the verification was Approved and can only be viewed for the first 10 minutes)
                        properties:
                          bankName:
                            type: string
                            description: Name of the bank of the account to be processed                            
                            maxLength: 30
                            example: Banco de la Republica
                          bankCode:
                            type: string
                            description: Code identifying the bank in the network                            
                            maxLength: 17
                            example: 001
                          accountType:
                            type: string
                            description: Account type
                            enum:
                              - SAV
                              - DDA
                            example: SAV
                          accountNumber:
                            type: string
                            description: Account number                            
                            maxLength: 17
                            example: 12345678901234567
                          franchise:
                            type: string
                            description: Franchise                            
                            maxLength: 17
                            example: VISA
                          verificationCode:
                            type: string
                            description: The verificationCode is a JSON Web Signature (JWS). It is used as the instrument to verify the account status.                            
                            example: eyJhbGciOiJSUzI1NiJ9.eyJhY2NvdW50SGFzaCI6ImM5YWM2ZjFhZDhjNDA3Y2ZjNzMyNDljNTE2MTJjNTdmMWQxZGNiNTA4YjE4ZGJlYWE1MWQ0NDI5NjBjMjUwNDUyMzY4ZTg2YmUzMWQ3MDMxMDY4ZDM2MjM2NzVjYzhkYTUzNzhhODNmMTUwZjg5OTczOTBiZTEyMGU1ZmExN2RhIiwib25UZXN0Ijp0cnVlLCJzZXJ2aWNlIjoibW9jayIsImlkIjo0MDB9.dFMY4EwCrWq9EBmERFkKCoLHExPH4vgaCgnZaqB_mf8n3Sv6Qnu6Pb79onluX1OZecmYmBuHqZ_ykKXWSD4RMZSpckYFCiO3mlcJKI4qb91COhl_c2qXxYJuLEdbLfGlzf0k8-oJgFcO9gAS1Xm0hpTP4iiXF6st1hFwlfR3fpX4rr-bTsKgMvRSReMuxa0Vs92DykfqUR_3udlc0DFCPB9ZTaSqeRNHFAPAWNniUPWURQlW5c9J9xcyKTgKGzfI1_7h2I4ALQeRifptE2nC-HZtEMwtcToNh7hn0oL9lNFXnXGK9sWKORcyWKVfpEChS8z30UfX6kOhU6fp_qUwmA
        "400":
          description: Invalid request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: "../base/en.yaml#/components/schemas/Status"
                required:
                  - status
  /api/validate-existing-account:
    post:
      summary: "Validate Existing Account"
      description: "Once the initial session creation has been successfully completed, you can perform validations on the account as many times as needed. You only need the account information and the verification code provided in the previous process."
      operationId: "validate-existing-account"
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: object
              required:
                - auth
                - account
              properties:
                auth: 
                  $ref: "../base/en.yaml#/components/schemas/Authentication"
                account:
                  type: object
                  description: Account to be validated. The verification code is required.
                  required:
                    - name
                    - email
                  properties:
                    bankName:
                      type: string
                      description: Name of the bank of the account to be processed
                      maxLength: 30
                      example: Banco de la Republica
                    bankCode:
                      type: string
                      description: Code identifying the bank in the network
                      maxLength: 17
                      example: 001
                    accountType:
                      type: string
                      description: Account type
                      enum:
                        - SAV
                        - DDA
                        - CCD
                      example: SAV
                    accountNumber:
                      type: string
                      description: Account number
                      maxLength: 17
                      example: 12345678901234567
                    franchise:
                      type: string
                      description: Franchise
                      maxLength: 20
                      example: VISA
                    verificationCode:
                      type: string
                      description: The verificationCode is a JSON Web Signature (JWS). It is used as the instrument to verify the account status.
                      example: eyJhbGciOiJSUzI1NiJ9.eyJhY2NvdW50SGFzaCI6ImM5YWM2ZjFhZDhjNDA3Y2ZjNzMyNDljNTE2MTJjNTdmMWQxZGNiNTA4YjE4ZGJlYWE1MWQ0NDI5NjBjMjUwNDUyMzY4ZTg2YmUzMWQ3MDMxMDY4ZDM2MjM2NzVjYzhkYTUzNzhhODNmMTUwZjg5OTczOTBiZTEyMGU1ZmExN2RhIiwib25UZXN0Ijp0cnVlLCJzZXJ2aWNlIjoibW9jayIsImlkIjo0MDB9.dFMY4EwCrWq9EBmERFkKCoLHExPH4vgaCgnZaqB_mf8n3Sv6Qnu6Pb79onluX1OZecmYmBuHqZ_ykKXWSD4RMZSpckYFCiO3mlcJKI4qb91COhl_c2qXxYJuLEdbLfGlzf0k8-oJgFcO9gAS1Xm0hpTP4iiXF6st1hFwlfR3fpX4rr-bTsKgMvRSReMuxa0Vs92DykfqUR_3udlc0DFCPB9ZTaSqeRNHFAPAWNniUPWURQlW5c9J9xcyKTgKGzfI1_7h2I4ALQeRifptE2nC-HZtEMwtcToNh7hn0oL9lNFXnXGK9sWKORcyWKVfpEChS8z30UfX6kOhU6fp_qUwmA
                payment:
                  type: object
                  description: Structure containing information about the transaction payment.
                  required:
                    - name
                    - email
                  properties:
                    amount:
                      type: object
                      description: Structure containing information about the transaction payment.
                      properties:
                        currency:
                          type: string
                          description: Currency code
                          minLength: 3
                          maxLength: 3
                          example: USD
                        total:
                          type: number
                locale:
                  type: string
                  default: en
                  example: es_CO
                site:
                  type: string
                  description: If use api credentials, this field is required to identificate the site
                  example: aabbccdd1234567890aabbccdd123456

      responses:
        "200":
          description: "Validation status response"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: "../base/en.yaml#/components/schemas/Status"
                required:
                  - status
        "400":
          description: |
            Invalid request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: "../base/en.yaml#/components/schemas/Status"
                required:
                  - status