openapi: 3.1.0
info:
  title: PlacetoPay Account Validator
  version: '1.0'
  description: |
    Account Validator es un proyecto encargado de la verificación de cuentas a través de servicios externos.
  contact:
    url: 'https://www.evertecinc.com/pasarela-de-pagos-e-commerce/'
    name: PlacetoPay by Evertec
servers:
  - description: 'Sandbox (CO)'
    url: 'https://sites-test.placetopay.com/'
paths:
  /api/create-session:
    post:
      summary: "Crear Session"
      description: "Este endpoint permite crear una sesión de verificación de cuenta"
      operationId: "create-session"
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: object
              required:
                - auth
                - user
                - returnUrl
                - locale
              properties:
                auth: 
                  $ref: "../base/es.yaml#/components/schemas/Authentication"
                user:
                  type: object
                  description: |
                    Usuario dueño de la cuenta a validar
                  required:
                      - name
                      - email
                  properties:
                    name:
                      type: string
                      description: Primer nombre o nombres del usuario propietario de la cuenta
                      maxLength: 50
                      example: John
                    surname:
                      type: string
                      description: Apellidos del usuario propietario de la cuenta
                      maxLength: 50
                      example: Due
                    email:
                      type: email
                      description: Correo Electrónico del usuario propietario de la cuenta
                      maxLength: 80
                      example: John.doe@test.com
                returnUrl:
                  type: string
                  description: Url de retorno una vez culmine el proceso de validación de cuentas
                  maxLength: 255
                  example: https://www.placetopay.com/return
                locale:
                  type: string
                  description: Determina el idioma de la respuesta
                  example: es_CO
                isAuthenticated:
                  type: boolean
                  description: Determina si ya se ha realizado un proceso de autenticación externa. La intención de no validar el correo electrónico del usuario dos veces. por defecto es false, quiere decir que se realizara envio de OTP para validar el usuario si este ya ha validado cuentas con microdepositos en el sistema
                  example: true
                site:
                  type: string
                  description: Si se usan credenciales API, se debe enviar el identificador del sitio
                  example: aabbccdd1234567890aabbccdd123456
      responses:
        "200":
          description: "Sesión creada exitosamente"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    description: Estructura que contiene la respuesta a la solicitud en el caso de que el estado sea exitoso
                    properties:
                      requestId:
                        type: string
                        description: Identificador unico de la sesión que desea consultar.
                        maxLength: 36
                        format: regex
                        pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
                        example: 9bd89c8d-6097-4d69-8ce9-d9b5ec35d8ea
                      redirectUrl:
                        type: string <url>
                        description: URL de redireccionamiento
                        example: https://dev-account-validator.placetopay.ws/verification/redirect/9bd89c8d-6097-4d69-8ce9-d9b5ec35d8ea
                      expiresAt:
                        type: string
                        description: Fecha de expiración de la sesión                          
                        example: 2024-04-19 17:36:57
                  status:
                    $ref: "../base/es.yaml#/components/schemas/Status"
                required:
                  - status
        "400":
          description: Petición inválida.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: "../base/es.yaml#/components/schemas/Status"
                required:
                  - status
  /api/check-session-status:
    post:
      summary: "Consultar estado de sesión"
      description: "Este endpoint te permitirá consultar el estado de la sesión creada."
      operationId: check-session-status
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: object
              properties:
                auth: 
                  $ref: "../base/es.yaml#/components/schemas/Authentication"
                requestId:
                  type: string
                  description: Identificador unico de la sesión que desea consultar.
                  maxLength: 36
                  example: 1f630ff7-9c02-4da4-82d4-d676709acb21
                site:
                  type: string
                  description: Si se usan credenciales API, se debe enviar el identificador del sitio                    
                  example: aabbccdd1234567890aabbccdd123456
              required:
                - auth
                - requestId
      responses:
        "200":
          description: "Consulta exitosa"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: "../base/es.yaml#/components/schemas/Status"                  
                  data:
                    type: object
                    description: Estructura que contiene la respuesta a la solicitud en el caso de que el estado sea exitoso
                    properties:
                      requestId:
                        type: string
                        description: Identificador unico de la sesión que desea consultar.
                        example: 1f630ff7-9c02-4da4-82d4-d676709acb21
                      expiresAt:
                        type: string
                        description: Fecha de expiración de la sesión                          
                        example: 2022-08-30 15:19:33
                      account:
                        type: object
                        description: Información de la cuenta verificada (este campo está disponible solo si la verificación fue Aprobada y solo podrá ser visualizada los 10 primero minutos)
                        properties:
                          bankName:
                            type: string
                            description: Nombre del banco de la cuenta a procesar
                            maxLength: 30
                            example: Banco de la Republica
                          bankCode:
                            type: string
                            description: Código que identifica al banco en la red                            
                            maxLength: 17
                            example: 001
                          accountType:
                            type: string
                            description: Tipo de cuenta
                            enum:
                              - SAV
                              - DDA
                            example: SAV
                          accountNumber:
                            type: string
                            description: Número de cuenta
                            maxLength: 17
                            example: 1234567890123456789
                          franchise:
                            type: string
                            description: Franchise
                          verificationCode:
                            type: string
                            description: El verificationCode es un JSON Web Signature (JWS). Tiene el fin de ser el instrumento verificador del estado de la cuenta.
                            example: eyJhbGciOiJSUzI1NiJ9.eyJhY2NvdW50SGFzaCI6ImM5YWM2ZjFhZDhjNDA3Y2ZjNzMyNDljNTE2MTJjNTdmMWQxZGNiNTA4YjE4ZGJlYWE1MWQ0NDI5NjBjMjUwNDUyMzY4ZTg2YmUzMWQ3MDMxMDY4ZDM2MjM2NzVjYzhkYTUzNzhhODNmMTUwZjg5OTczOTBiZTEyMGU1ZmExN2RhIiwib25UZXN0Ijp0cnVlLCJzZXJ2aWNlIjoibW9jayIsImlkIjo0MDB9.dFMY4EwCrWq9EBmERFkKCoLHExPH4vgaCgnZaqB_mf8n3Sv6Qnu6Pb79onluX1OZecmYmBuHqZ_ykKXWSD4RMZSpckYFCiO3mlcJKI4qb91COhl_c2qXxYJuLEdbLfGlzf0k8-oJgFcO9gAS1Xm0hpTP4iiXF6st1hFwlfR3fpX4rr-bTsKgMvRSReMuxa0Vs92DykfqUR_3udlc0DFCPB9ZTaSqeRNHFAPAWNniUPWURQlW5c9J9xcyKTgKGzfI1_7h2I4ALQeRifptE2nC-HZtEMwtcToNh7hn0oL9lNFXnXGK9sWKORcyWKVfpEChS8z30UfX6kOhU6fp_qUwmA
        "400":
          description: Solicitud inválida.
          content:
            application/json:
              schema:
                type: object
                properties:                  
                  status:
                    $ref: "../base/es.yaml#/components/schemas/Status"
                required:
                  - status
  /api/validate-existing-account:
    post:
      summary: "Validar Cuenta existente"
      description: "Una vez realizada de manera exitosa la creación inicial de la sesión podrá realizar validaciones a la cuenta las veces que considere necesarias, solo debe tener la información de la cuenta y el código de verificación entregado en el proceso anterior."
      operationId: "validate-existing-account"
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: object
              required:
                - auth
                - user
              properties:
                auth: 
                  $ref: "../base/es.yaml#/components/schemas/Authentication"
                account:
                  type: object
                  description: Cuenta a la que se le realizará la validación. El código de verificación es requerido.
                  required:
                    - name
                    - email
                  properties:
                    bankName:
                      type: string
                      description: Nombre del banco de la cuenta a procesar
                      maxLength: 30
                      example: Banco de la Republica
                    bankCode:
                      type: string
                      description: Código que identifica al banco en la red
                      maxLength: 17
                      example: 001
                    accountType:
                      type: string
                      description: Tipo de cuenta
                      enum:
                        - SAV
                        - DDA
                        - CCD
                      example: SAV
                    accountNumber:
                      type: string
                      description: Número de cuenta
                      maxLength: 17
                      example: 1234567890123456789
                    franchise:
                      type: string
                      description: Franchise
                      maxLength: 20
                      example: VISA
                    verificationCode:
                      type: string
                      description: El verificationCode es un JSON Web Signature (JWS). Tiene el fin de ser el instrumento verificador del estado de la cuenta.
                        
                      example: eyJhbGciOiJSUzI1NiJ9.eyJhY2NvdW50SGFzaCI6ImM5YWM2ZjFhZDhjNDA3Y2ZjNzMyNDljNTE2MTJjNTdmMWQxZGNiNTA4YjE4ZGJlYWE1MWQ0NDI5NjBjMjUwNDUyMzY4ZTg2YmUzMWQ3MDMxMDY4ZDM2MjM2NzVjYzhkYTUzNzhhODNmMTUwZjg5OTczOTBiZTEyMGU1ZmExN2RhIiwib25UZXN0Ijp0cnVlLCJzZXJ2aWNlIjoibW9jayIsImlkIjo0MDB9.dFMY4EwCrWq9EBmERFkKCoLHExPH4vgaCgnZaqB_mf8n3Sv6Qnu6Pb79onluX1OZecmYmBuHqZ_ykKXWSD4RMZSpckYFCiO3mlcJKI4qb91COhl_c2qXxYJuLEdbLfGlzf0k8-oJgFcO9gAS1Xm0hpTP4iiXF6st1hFwlfR3fpX4rr-bTsKgMvRSReMuxa0Vs92DykfqUR_3udlc0DFCPB9ZTaSqeRNHFAPAWNniUPWURQlW5c9J9xcyKTgKGzfI1_7h2I4ALQeRifptE2nC-HZtEMwtcToNh7hn0oL9lNFXnXGK9sWKORcyWKVfpEChS8z30UfX6kOhU6fp_qUwmA
                payment:
                  type: object
                  description: Estructura que contiene la información acerca del pago de la transacción.
                  required:
                    - amount
                  properties:
                    amount:
                      type: object
                      description: Estructura que contiene la información acerca del pago de la transacción.
                      properties:
                        currency:
                          type: string
                          description: Moneda
                          maxLength: 3
                          minLength: 3
                          example: USD
                        total:
                          type: number
                          description: Monto
                          example: 100
                locale:
                  type: string
                  description: Idioma
                  default: en
                  example: es_CO
                site:
                  type: string
                  description: Si se usan credenciales API, se debe enviar el identificador del sitio                    
                  example: aabbccdd1234567890aabbccdd123456

      responses:
        "200":
          description: "Respuesta estado de validación"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: "../base/es.yaml#/components/schemas/Status"
        "400":
          description: Solicitud inválida.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: "../base/es.yaml#/components/schemas/Status"
